apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-alertmanager
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
    component: alertmanager
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prom-stack-chart.selectorLabels" . | nindent 4 }}
    component: alertmanager
