apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-grafana
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prom-stack-chart.selectorLabels" . | nindent 6 }}
      component: grafana
  template:
    metadata:
      labels:
        {{- include "prom-stack-chart.selectorLabels" . | nindent 8 }}
        component: grafana
    spec:
      serviceAccountName: {{ include "prom-stack-chart.serviceAccountName" . }}
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
