apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-grafana
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
    component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "prom-stack-chart.selectorLabels" . | nindent 4 }}
    component: grafana
