apiVersion: v1
kind: Service
metadata:
  name: prometheus-prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: node-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: prometheus
    component: node-exporter
