apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-pushgateway
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
    component: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prom-stack-chart.selectorLabels" . | nindent 6 }}
      component: pushgateway
  template:
    metadata:
      labels:
        {{- include "prom-stack-chart.selectorLabels" . | nindent 8 }}
        component: pushgateway
    spec:
      serviceAccountName: {{ include "prom-stack-chart.serviceAccountName" . }}
      containers:
        - name: pushgateway
          image: "{{ .Values.pushgateway.image.repository }}:{{ .Values.pushgateway.image.tag }}"
          imagePullPolicy: {{ .Values.pushgateway.image.pullPolicy }}
          ports:
            - containerPort: 9091
              name: http
          resources:
            {{- toYaml .Values.pushgateway.resources | nindent 12 }}
