apiVersion: v1
kind: Service
metadata:
  name: prometheus-prometheus-pushgateway
  namespace: monitoring
  labels:
    app: prometheus
    component: pushgateway
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: prometheus
    component: pushgateway
