apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-loki
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
spec:
  {{- $loki := .Values.loki | default dict }}
  {{- $service := $loki.service | default dict }}
  type: {{ $service.type | default "ClusterIP" }}
  ports:
    - port: {{ $service.port | default 3100 }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    - port: {{ $service.memberlistPort | default 7946 }}
      targetPort: memberlist
      protocol: TCP
      name: memberlist
  selector:
    {{- include "prom-stack-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loki
