apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-loki
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    - port: {{ .Values.loki.service.memberlistPort }}
      targetPort: memberlist
      protocol: TCP
      name: memberlist
  selector:
    {{- include "prom-stack-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loki
