apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-prometheus
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
    component: prometheus
spec:
  serviceName: {{ include "prom-stack-chart.fullname" . }}-prometheus
  replicas: 1
  selector:
    matchLabels:
      {{- include "prom-stack-chart.selectorLabels" . | nindent 6 }}
      component: prometheus
  template:
    metadata:
      labels:
        {{- include "prom-stack-chart.selectorLabels" . | nindent 8 }}
        component: prometheus
    spec:
      serviceAccountName: {{ include "prom-stack-chart.serviceAccountName" . }}
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.retention }}"
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: storage-volume
              mountPath: /prometheus
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "prom-stack-chart.fullname" . }}-prometheus
  {{- if .Values.prometheus.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: storage-volume
      spec:
        accessModes:
          - {{ .Values.prometheus.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.prometheus.persistence.size | quote }}
        {{- if .Values.prometheus.persistence.storageClass }}
        storageClassName: {{ .Values.prometheus.persistence.storageClass | quote }}
        {{- end }}
  {{- else }}
      volumes:
        - name: storage-volume
          emptyDir: {}
  {{- end }}
